import Vuex from 'vuex'

const store = new Vuex.Store({
  state: {
    articles: [{
      id: '7595',
      slug: 'comment-aider-mes-clients-gt-a-prendre-une-decision-sur-un-candidat-et-a-preparer-sa-proposition',
      title: 'Comment aider mes clients GT à prendre une décision sur un candidat et à préparer sa proposition',
      publicationDate: '2017/03/17',
      readingTime: '1 min',
      summary: 'Recruter une nouvelle personne au sein de la Theodo Academy n’est pas une décision facile. Ton candidat a passé tous ses entretiens et il s’agit maintenant pour le CEO et le CTO d’une startup de la TA de prendre la décision ou non de lui faire une proposition. Voici ce dont ils ont besoin :…',
      content: '<p class="selectionShareable">Recruter une nouvelle personne au sein de la Theodo Academy n’est pas une décision facile.</p><p class="selectionShareable">Ton candidat a passé tous ses entretiens et il s’agit maintenant pour le CEO et le CTO d’une startup de la TA de prendre la décision ou non de lui faire une proposition. Voici ce dont ils ont besoin :</p><ul><li>Le CV à jour du candidat imprimé</li><li>Le compte rendu de tous ses entretiens. Sur ce CR tu as noté&nbsp;:<ul><li>Les nom prénoms du candidat</li><li>Le poste (Dev, Biz, UX ou OPS)</li><li>Son ou ses école(s)</li><li>Le contrat souhaité (Césure, SFE ou CDI).<br>Attention un Biz qui postule en SFE aura un contrat de stage.</li><li>Les étoiles obtenues pour chaque entretien hors GT (Exemple 2 x 3* + 3 x 4*)</li></ul></li><li>Ta recommandation&nbsp;: GO ou NO GO + précision si nécessaire<br><em>Exemple GO mais doit se former au technos web avec son coach avant son arrivée</em></li></ul><p class="selectionShareable"><a href="http://www.theodo.fr/uploads/blog//2017/03/Capture-d’écran-2017-03-17-à-14.18.35.png" class="fluidbox fluidbox-closed" id="fluidbox-1"><div class="fluidbox-wrap" style="z-index: 990;"><img class="alignnone size-medium wp-image-7596" src="http://www.theodo.fr/uploads/blog//2017/03/Capture-d’écran-2017-03-17-à-14.18.35-300x166.png" alt="Capture d’écran 2017-03-17 à 14.18.35" width="300" height="166" style="opacity: 1;"><div class="fluidbox-ghost" style="width: 300px; height: 72px; top: 0px; left: 0px;"></div><div class="fluidbox-loader" style="width: 300px; height: 72px; top: 0px; left: 0px;"></div></div></a></p><p class="selectionShareable">&nbsp;</p><p class="selectionShareable">Bonne nouvelle&nbsp;!! Nous décidons de faire une proposition à ton candidat. Voici comment aider tes clients à la préparer&nbsp;:</p><ul><li>Tu as une salle réservée et pour la durée standard selon le candidat.<br>Attention pour Julien et Benoit toutes les propositions se font dans la salle Eurostar.</li><li>Dès que tu as le Go tu envoies un mail à Julien et Benoit ou aux CEO + CTO de la startup TA avec les infos suivantes&nbsp;:<ul><li>Prénom Nom</li><li>Ecole(s) + année d’obtention du dernier diplome</li><li>Poste souhaité au sein de Theodo (Dev, Biz, UX ou OPS)</li><li>Type de contrat souhaité (Césure, SFE ou CDI)</li><li>Années d’expérience post-diplôme</li><li>Pistes en cours et statut d’avancement</li><li>Rémunération actuelle si possible (fixe + variable)</li><li>Rémunération souhaitée</li><li>CV du candidat en pièce jointe</li><li>CR de ses entretiens en pièce jointe</li></ul></li></ul><p class="selectionShareable"><a href="http://www.theodo.fr/uploads/blog//2017/03/Capture-d’écran-2017-03-17-à-15.08.58.png" class="fluidbox fluidbox-closed" id="fluidbox-2"><div class="fluidbox-wrap" style="z-index: 990;"><img class="alignnone size-medium wp-image-7598" src="http://www.theodo.fr/uploads/blog//2017/03/Capture-d’écran-2017-03-17-à-15.08.58-300x156.png" alt="Capture d’écran 2017-03-17 à 15.08.58" width="300" height="156" style="opacity: 1;"><div class="fluidbox-ghost" style="width: 300px; height: 72px; top: 0px; left: 0px;"></div><div class="fluidbox-loader" style="width: 300px; height: 72px; top: 0px; left: 0px;"></div></div></a></p><ul><li>1h avant la proposition au plus tard, tu imprimes ton mail + le CV + le CR des entretiens et tu transmets ces documents à la personne qui va faire la proposition</li><li>Dans la salle de la proposition, tu mets&nbsp;4-5 feuilles de papier blanc A4 + 1 stylo pour la personne qui fera la proposition</li></ul><p class="selectionShareable">&nbsp;</p><hr><p class="selectionShareable">You liked this article? You\'d probably be a good match for our ever-growing tech team at Theodo. </p><p style="text-align: center;" class="selectionShareable"><a target="_blank" href="//www.theodo.com?utm_source=blog_article_joinus_button&amp;utm_medium=blog&amp;utm_campaign=blog" class="button"><i class="pw-icon-heart"></i>Join Us</a></p>',
      author: {
        name: 'Maxime Catta',
        slug: 'maximectheodo-fr',
        picture: 'https://lh5.googleusercontent.com/-Z4h9EuCoMZU/AAAAAAAAAAI/AAAAAAAAABI/8d7_TlUovlE/photo.jpg'
      },
      tags: [
        { name: 'Hiring', slug: 'internal/hiring' },
        { name: 'Internal', slug: 'internal' }
      ]
    }],
    authors: [
      { id: '1', slug: 'fabrice-bernhard', picture: 'https://lh5.googleusercontent.com/-RW5TdAjtt7I/AAAAAAAAAAI/AAAAAAAADPk/Lqm6QdJWIHw/photo.jpg' },
      { id: '3', slug: 'benjamin-grandfond', picture: 'https://lh4.googleusercontent.com/-NAvg5cc930k/AAAAAAAAAAI/AAAAAAAAA3Q/ABqwbA3PPYw/photo.jpg' },
      { id: '11', slug: 'marek-kalnik', picture: 'http://0.gravatar.com/avatar/390ceb969765e94af7d45c320f0d446c?s=96&amp;d=mm&amp;r=g' },
      { id: '42', slug: 'tristanr', picture: 'https://lh3.googleusercontent.com/-fo3NmxiZBvE/AAAAAAAAAAI/AAAAAAAAANs/_tEDWqwhrf4/photo.jpg' },
      { id: '116', slug: 'flavianhtheodo-fr', picture: 'https://lh6.googleusercontent.com/-qSaDRygXMPU/AAAAAAAAAAI/AAAAAAAAAA4/MbYk6Nk0PG0/photo.jpg' },
      { id: '50', slug: 'nicolasg', picture: 'https://lh4.googleusercontent.com/-gpQ7ZtHlIUI/AAAAAAAAAAI/AAAAAAAAApY/KJb8tx8qONY/photo.jpg' },
      { id: '38', slug: 'raphaeld', picture: 'https://lh3.googleusercontent.com/-ZBSx8DBCFcY/AAAAAAAAAAI/AAAAAAAAArM/n9-KmiIIymM/photo.jpg' },
      { id: '23', slug: 'jonathanb', picture: 'https://lh6.googleusercontent.com/-ktia87xknc4/AAAAAAAAAAI/AAAAAAAAArk/Haj3LWoASHo/photo.jpg' },
      { id: '12', slug: 'pierre-henri-cumenge', picture: 'https://lh6.googleusercontent.com/-OBuiujjMiXA/AAAAAAAAAAI/AAAAAAAABG4/BXia7HO5fuY/photo.jpg' },
      { id: '67', slug: 'tristanp', picture: 'http://0.gravatar.com/avatar/91e6fe3d348edb9023eb4cbf04cb3b88?s=96&amp;d=mm&amp;r=g' },
      { id: '120', slug: 'louisztheodo-fr', picture: 'https://lh5.googleusercontent.com/-dC2qhmu98NE/AAAAAAAAAAI/AAAAAAAAABQ/C6v0yGvDjcI/photo.jpg' },
      { id: '57', slug: 'woodyr', picture: 'https://lh4.googleusercontent.com/-sxw_1a-tRts/AAAAAAAAAAI/AAAAAAAAABw/aO5DBYuimVU/photo.jpg' },
      { id: '129', slug: 'sammyttheodo-fr', picture: 'https://lh6.googleusercontent.com/-uXxOquAqtfM/AAAAAAAAAAI/AAAAAAAAADw/7fjiS2ruQs8/photo.jpg' },
      { id: '51', slug: 'nicolasgo', picture: 'https://lh4.googleusercontent.com/-AAJEHOTrnbE/AAAAAAAAAAI/AAAAAAAAAt0/HNG-C2xkeNQ/photo.jpg' },
      { id: '93', slug: 'vincentl', picture: 'https://lh4.googleusercontent.com/-z8QsGYGPS9s/AAAAAAAAAAI/AAAAAAAAAVk/cgp9SB0M3eE/photo.jpg' },
      { id: '31', slug: 'reynaldm', picture: 'https://lh4.googleusercontent.com/-pedoNeAkPCo/AAAAAAAAAAI/AAAAAAAAANg/Ho0VxoeeqGw/photo.jpg' },
      { id: '34', slug: 'matthieua', picture: 'https://lh3.googleusercontent.com/-KL35SVHj9s0/AAAAAAAAAAI/AAAAAAAAAQs/nrnZdlrztM0/photo.jpg' },
      { id: '14', slug: 'remy-luciani', picture: 'https://lh5.googleusercontent.com/-e9pvXJz0AfA/AAAAAAAAAAI/AAAAAAAAAUs/EgtvHMRT2fk/photo.jpg' },
      { id: '5', slug: 'cyrille-jouineau', picture: 'http://0.gravatar.com/avatar/9981d17b10341449def466cbbad03e90?s=96&amp;d=mm&amp;r=g' },
      { id: '71', slug: 'vincentq', picture: 'https://lh6.googleusercontent.com/-07AFk7QRKTo/AAAAAAAAAAI/AAAAAAAAABQ/i2KpRR81ApQ/photo.jpg' },
      { id: '86', slug: 'thibautgtheodo-fr', picture: 'https://lh4.googleusercontent.com/-hZ1kd6WbzBk/AAAAAAAAAAI/AAAAAAAAA68/oWAcFBKPDfw/photo.jpg' },
      { id: '95', slug: 'antoinettheodo-fr', picture: 'https://lh3.googleusercontent.com/-k6Kk57J6aXw/AAAAAAAAAAI/AAAAAAAAAEs/__BYOeX-7Lw/photo.jpg' },
      { id: '74', slug: 'samptheodo-co-uk', picture: 'https://lh6.googleusercontent.com/-U1Ugk3L-uHg/AAAAAAAAAAI/AAAAAAAAAA4/3SOdWCIBI8I/photo.jpg' },
      { id: '146', slug: 'foucaulddtheodo-fr', picture: 'https://lh4.googleusercontent.com/-9DKQ7NbVnY4/AAAAAAAAAAI/AAAAAAAAACc/wYktTuX0CNI/photo.jpg' },
      { id: '64', slug: 'thibautc', picture: 'https://lh6.googleusercontent.com/-hNOWQpGH-II/AAAAAAAAAAI/AAAAAAAAAjc/vsnq4tnUR2U/photo.jpg' },
      { id: '62', slug: 'alberict', picture: 'http://0.gravatar.com/avatar/98e2ecda51b3cd3b58f9f42b0936d190?s=96&amp;d=mm&amp;r=g' },
      { id: '76', slug: 'nathangtheodo-fr', picture: 'https://lh3.googleusercontent.com/-kF-T1rGlhaY/AAAAAAAAAAI/AAAAAAAAADI/nL0AhoAYKCw/photo.jpg' },
      { id: '46', slug: 'marcpp', picture: 'https://lh4.googleusercontent.com/-BENafXtzjjI/AAAAAAAAAAI/AAAAAAAAAC0/vjh4ZGUS9qs/photo.jpg' },
      { id: '26', slug: 'guillaumed', picture: 'http://1.gravatar.com/avatar/752488139235b7f2b12fd81a55dd261d?s=96&amp;d=mm&amp;r=g' },
      { id: '128', slug: 'nicolastrtheodo-fr', picture: 'https://lh5.googleusercontent.com/-q3rKHWSOg-k/AAAAAAAAAAI/AAAAAAAAABg/q69iCHhyMmk/photo.jpg' },
      { id: '111', slug: 'cedricktheodo-fr', picture: 'https://lh5.googleusercontent.com/-kX5u7axPogM/AAAAAAAAAAI/AAAAAAAAAD4/xxM_P1IDVkI/photo.jpg' },
      { id: '20', slug: 'thierrym', picture: 'http://0.gravatar.com/avatar/031b291beb642221a86d0f05b11b8c6e?s=96&amp;d=mm&amp;r=g' },
      { id: '18', slug: 'nicolasb', picture: 'https://lh5.googleusercontent.com/--YIJ67aaPww/AAAAAAAAAAI/AAAAAAAAABY/mKvnClEjk64/photo.jpg' },
      { id: '125', slug: 'nicolasntheodo-fr', picture: 'https://lh5.googleusercontent.com/-kEsi_jK2Z_s/AAAAAAAAAAI/AAAAAAAAACI/0-TW1i7RnT4/photo.jpg' },
      { id: '43', slug: 'yannj', picture: 'https://lh6.googleusercontent.com/-3QQuK3xQreI/AAAAAAAAAAI/AAAAAAAAAIA/27vQXwhtRNM/photo.jpg' },
      { id: '87', slug: 'kevinrtheodo-fr', picture: 'https://lh4.googleusercontent.com/-ymjprx31EUc/AAAAAAAAAAI/AAAAAAAAAB0/lc8V0kohjus/photo.jpg' },
      { id: '48', slug: 'paulm', picture: 'https://lh5.googleusercontent.com/-hbggFqOuoC4/AAAAAAAAAAI/AAAAAAAAAFw/rf2D9Kmues0/photo.jpg' },
      { id: '122', slug: 'richardmtheodo-co-uk', picture: 'https://lh3.googleusercontent.com/-BxAJdlQSn-4/AAAAAAAAAAI/AAAAAAAAADc/g2HVdTod1CU/photo.jpg' },
      { id: '126', slug: 'jeremygtheodo-fr', picture: 'https://lh6.googleusercontent.com/-ud8TwKSGFSw/AAAAAAAAAAI/AAAAAAAAAKc/UAWIYV3yh5Y/photo.jpg' },
      { id: '131', slug: 'richardctheodo-fr', picture: 'https://lh5.googleusercontent.com/-i5xM5pdT-rQ/AAAAAAAAAAI/AAAAAAAAACc/Og7sB1eA0JY/photo.jpg' },
      { id: '124', slug: 'melchiormtheodo-fr', picture: 'https://lh4.googleusercontent.com/-lTgUf4sBfxU/AAAAAAAAAAI/AAAAAAAAABM/Y4uwEJrcCDQ/photo.jpg' },
      { id: '133', slug: 'pauljtheodo-fr', picture: 'https://lh4.googleusercontent.com/-W9R5yryCJEU/AAAAAAAAAAI/AAAAAAAAADI/3m4wMgm3NZg/photo.jpg' },
      { id: '132', slug: 'fernandobtheodo-fr', picture: 'https://lh6.googleusercontent.com/-Dk69IAIafds/AAAAAAAAAAI/AAAAAAAAABM/_HVkp4fuMKw/photo.jpg' },
      { id: '166', slug: 'victordtheodo-co-uk', picture: 'https://lh6.googleusercontent.com/-PfvXirhtnV8/AAAAAAAAAAI/AAAAAAAAAB4/AToLLhVFcSs/photo.jpg' },
      { id: '192', slug: 'pierreptheodo-fr', picture: 'https://lh6.googleusercontent.com/-rJXxgmbDqH0/AAAAAAAAAAI/AAAAAAAAABM/OHtrNi9eHGU/photo.jpg' },
      { id: '191', slug: 'georgesbtheodo-fr', picture: 'https://lh5.googleusercontent.com/-vm7j1-0toQA/AAAAAAAAAAI/AAAAAAAAAAs/WfT8x2ek8Vo/photo.jpg' },
      { id: '197', slug: 'guillaumertheodo-fr', picture: 'https://lh4.googleusercontent.com/-OXT7UVy8qNM/AAAAAAAAAAI/AAAAAAAAAAc/S_WrLJn6Vvg/photo.jpg' },
      { id: '209', slug: 'benetheodo-fr', picture: 'https://lh6.googleusercontent.com/-9owKawp-sQM/AAAAAAAAAAI/AAAAAAAAAAs/25P0JFZuQV8/photo.jpg' },
      { id: '211', slug: 'quentinftheodo-fr', picture: 'https://lh6.googleusercontent.com/-jZNBp6R5Uoo/AAAAAAAAAAI/AAAAAAAAAAo/DftsIp-FpwU/photo.jpg' },
      { id: '190', slug: 'alexandrectheodo-fr', picture: 'https://lh5.googleusercontent.com/-Qd4zgJ5HV5c/AAAAAAAAAAI/AAAAAAAAAAs/WywwDwsP_pI/photo.jpg' },
      { id: '180', slug: 'clementetheodo-fr', picture: 'https://lh5.googleusercontent.com/-NiuJQKP4vNE/AAAAAAAAAAI/AAAAAAAAAAk/5bHhDY9sJVs/photo.jpg' },
      { id: '160', slug: 'gregoirehtheodo-fr', picture: 'https://lh4.googleusercontent.com/-ZBulf2nMPYs/AAAAAAAAAAI/AAAAAAAAABs/MaCD5fokgcU/photo.jpg' },
      { id: '153', slug: 'damienptheodo-fr', picture: 'https://lh3.googleusercontent.com/-d592RLAASbA/AAAAAAAAAAI/AAAAAAAAAE8/lA5rpqJBgeM/photo.jpg' },
      { id: '162', slug: 'brunogtheodo-co-uk', picture: 'https://lh4.googleusercontent.com/-wRlx7jqk7_M/AAAAAAAAAAI/AAAAAAAAABM/giyDL0xvcrc/photo.jpg' },
      { id: '165', slug: 'jeremydtheodo-fr', picture: 'https://lh3.googleusercontent.com/-kOGGuu0_tRo/AAAAAAAAAAI/AAAAAAAAACU/DdYyDjR822g/photo.jpg' },
      { id: '168', slug: 'adrienatheodo-fr', picture: 'https://lh3.googleusercontent.com/-zXSn1tIjbQw/AAAAAAAAAAI/AAAAAAAAACo/On5vf5903EI/photo.jpg' },
      { id: '134', slug: 'haristheodo-co-uk', picture: 'https://lh5.googleusercontent.com/-gCQs3x4MEvQ/AAAAAAAAAAI/AAAAAAAAAFQ/y9ZAfSTVWAE/photo.jpg' },
      { id: '81', slug: 'maximestheodo-fr', picture: 'https://lh4.googleusercontent.com/-qT53-fBPVcU/AAAAAAAAAAI/AAAAAAAAABM/WdIedr7tcgc/photo.jpg' },
      { id: '52', slug: 'julienv', picture: 'http://1.gravatar.com/avatar/deec69853e6fa7fc2b04c8bb1fef06a3?s=96&amp;d=mm&amp;r=g' },
      { id: '49', slug: 'adrient', picture: 'http://2.gravatar.com/avatar/e1880082e75494a2b472e4d27705638f?s=96&amp;d=mm&amp;r=g' },
      { id: '53', slug: 'clementrp', picture: 'https://lh4.googleusercontent.com/-vERAtKLYy4w/AAAAAAAAAAI/AAAAAAAAAI8/gDAS4ceQjbg/photo.jpg' },
      { id: '55', slug: 'yulingc', picture: 'https://lh3.googleusercontent.com/-fyIlD38Tl-U/AAAAAAAAAAI/AAAAAAAAAUQ/utu_p_phb9Y/photo.jpg' },
      { id: '58', slug: 'rodolphedb', picture: 'https://lh6.googleusercontent.com/-199FLcQOM7k/AAAAAAAAAAI/AAAAAAAAAt8/chnGQa3onII/photo.jpg' },
      { id: '47', slug: 'jeanremib', picture: 'https://lh3.googleusercontent.com/-NM_5ExVI4Mo/AAAAAAAAAAI/AAAAAAAAAD0/k8hOHd7raYQ/photo.jpg' },
      { id: '44', slug: 'kingas', picture: 'http://2.gravatar.com/avatar/b98129f3a142fa9f99eeb3911cfb2838?s=96&amp;d=mm&amp;r=g' },
      { id: '21', slug: 'valentinb', picture: 'http://2.gravatar.com/avatar/2a3821fe5398b7a199df15585470f743?s=96&amp;d=mm&amp;r=g' },
      { id: '24', slug: 'nicolast', picture: 'https://lh5.googleusercontent.com/-MvuHLS-EjB4/AAAAAAAAAAI/AAAAAAAAACs/pyHG3EjMXO0/photo.jpg' },
      { id: '25', slug: 'kennyd', picture: 'http://2.gravatar.com/avatar/2471149ef2cb47af4640b18cfada33d2?s=96&amp;d=mm&amp;r=g' },
      { id: '39', slug: 'adlena', picture: 'http://1.gravatar.com/avatar/7854f3e5e0c39c4e66b2eef0cb9f2bff?s=96&amp;d=mm&amp;r=g' },
      { id: '90', slug: 'clemenththeodo-fr', picture: 'https://lh6.googleusercontent.com/-ThTVm10Bq9g/AAAAAAAAAAI/AAAAAAAAAnI/9OjbVoL8mzU/photo.jpg' },
      { id: '63', slug: 'jeanlucc', picture: 'https://lh5.googleusercontent.com/-v9enF0-Z7EQ/AAAAAAAAAAI/AAAAAAAAABM/mXdRuGn13XM/photo.jpg' },
      { id: '98', slug: 'kevinjtheodo-fr', picture: 'https://lh3.googleusercontent.com/-wc9zo36vNj4/AAAAAAAAAAI/AAAAAAAAACc/SEPcqqZnVYU/photo.jpg' },
      { id: '97', slug: 'charlesbtheodo-fr', picture: 'https://lh3.googleusercontent.com/-g4PHcXdL89s/AAAAAAAAAAI/AAAAAAAAAA8/g7l44EjeUPw/photo.jpg' },
      { id: '99', slug: 'farhanmtheodo-co-uk', picture: 'https://lh3.googleusercontent.com/-yv7c1efBvno/AAAAAAAAAAI/AAAAAAAAACM/fGrHgWwSbWQ/photo.jpg' },
      { id: '102', slug: 'samygtheodo-fr', picture: 'https://lh6.googleusercontent.com/-84dEP3QMusA/AAAAAAAAAAI/AAAAAAAAABQ/xArFJH51QZQ/photo.jpg' },
      { id: '110', slug: 'stanislasbtheodo-fr', picture: 'https://lh6.googleusercontent.com/-6wwNSdDK0VY/AAAAAAAAAAI/AAAAAAAAABM/mxm_tpiCDPg/photo.jpg' },
      { id: '96', slug: 'auroremtheodo-fr', picture: 'https://lh4.googleusercontent.com/-GwISjjonXUo/AAAAAAAAAAI/AAAAAAAAAA4/Y1pUb7dH_P4/photo.jpg' },
      { id: '92', slug: 'corentinbtheodo-fr', picture: 'https://lh6.googleusercontent.com/-QQ7z0JmFRSk/AAAAAAAAAAI/AAAAAAAAABA/Ul3XNzENrhY/photo.jpg' },
      { id: '66', slug: 'eduardos', picture: 'http://2.gravatar.com/avatar/eedbe06f8bfdbf5e743f27bcb49ac9b0?s=96&amp;d=mm&amp;r=g' },
      { id: '68', slug: 'benjaminb', picture: 'https://lh6.googleusercontent.com/-mEjvk0dRYF4/AAAAAAAAAAI/AAAAAAAAAKQ/uu-xcky0t2w/photo.jpg' },
      { id: '88', slug: 'cyrillehtheodo-fr', picture: 'https://lh5.googleusercontent.com/-GP6gPffExVA/AAAAAAAAAAI/AAAAAAAAAiE/9pVUqgPXlsA/photo.jpg' },
      { id: '91', slug: 'antoinektheodo-fr', picture: 'https://lh3.googleusercontent.com/-1kot1jxajXQ/AAAAAAAAAAI/AAAAAAAAAaA/qbuXixqacag/photo.jpg' },
      { id: '112', slug: 'thibaultctheodo-fr', picture: 'https://lh3.googleusercontent.com/-T9XvxBlcMUY/AAAAAAAAAAI/AAAAAAAAABM/Oq6UYmuASXo/photo.jpg' }
    ]
  },
  mutations: {}
})

export default store
